spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/excel_db?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: zhao-ang
    password: 114514
  servlet:
    multipart:
      max-file-size: 500MB     #单文件上传大小
      max-request-size: 500MB  #总文件